### ISSUE TITLE
CI doesn't check the crate using 1.34.0

### ISSUE THREAD

**Issue by Lokathor** [Frommi/miniz_oxide#90]
The readme says that the crate should build with 1.34.0, but this isn't confirmed on a regular basis by the CI.

**Comment by Alphare** [comment]
I am trying to use `zstd-rs` (to implement some of the core tools within Mercurial), which has a dependency on `miniz_oxide`. Trying to build using `1.34.2` (the latest version available on Debian stable) yields the following error:

```
error[E0658]: use of unstable library feature 'alloc': this library is unlikely to be stabilized in its current form or name (see issue #27783)
  --> /home/alphare/.cargo/registry/src/github.com-1ecc6299db9ec823/miniz_oxide-0.4.0/src/lib.rs:28:1
   |
28 | extern crate alloc;
   | ^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `miniz_oxide`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

Looking at the code, there does not seem to be a feature flag guarding the `extern crate alloc` statement, making this crate at least compatible with `1.36+`, not `1.34`, which is a bummer.
